### ISSUE TITLE
Flags not set for LD A, R and LD A, I

### ISSUE THREAD

**Issue by fruit-bat** [DrGoldfire/Z80.js#5]
Excellent Z80 emulation, many thanks!

Some code uses these flags in loops (e.g. Scott Adams). I think the following is correct but please check...

Try...

// 0x5f : LD A, R
Z80.prototype.ed_instructions[0x5f] = function() {
   this.a = this.r;
   this.flags.P = this.iff2;
   this.flags.S = (this.a & 0x80) !== 0;
   this.flags.X = (this.a & 0x08) !== 0;
   this.flags.Y = (this.a & 0x20) !== 0;
   this.flags.Z = this.a === 0;
   this.flags.H = 0;
   this.flags.N = 0;
};

// 0x57 : LD A, I
Z80.prototype.ed_instructions[0x57] = function() {
   this.a = this.i;
   this.flags.P = this.iff2;
   this.flags.S = (this.a & 0x80) !== 0;
   this.flags.X = (this.a & 0x08) !== 0;
   this.flags.Y = (this.a & 0x20) !== 0;
   this.flags.Z = this.a === 0;
   this.flags.H = 0;
   this.flags.N = 0;
};

**Comment by fruit-bat** [comment]
Oh, looks like you may have already fixed LD A, I
I must have an older copy. LD A,R still missing flags.

**Comment by DrGoldfire** [comment]
Thanks for reporting this. You're right, `LD A, I` was PR #3, but it didn't include the X and Y flags and nothing's been done about flags for `LD A, R` at all. Every source I can find says the flags should be set the same way for both instructions, so your suggestion is pretty much correct; I'll get a patch put together.
